# Generated by Django 4.2.1 on 2023-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('service_fee', models.PositiveBigIntegerField(verbose_name='Price')),
                ('service_cost', models.PositiveBigIntegerField(verbose_name='Cost')),
            ],
        ),
    ]
