# Generated by Django 4.2.1 on 2023-05-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(auto_created=True)),
                ('customer_name', models.CharField(max_length=60, verbose_name='Customer Name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_ref', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_amount', models.PositiveBigIntegerField(verbose_name='Total')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
            ],
        ),
    ]
